stages:
  decompress:
    cmd: unzip data.zip
    deps:
      - data.zip
    outs:
      - dataset-landscape-main
  train:
    cmd: python -m compression train
    params:
      - train_data
      - learning_rate
      - image_size
      - model_path
    deps:
      - ${train_data}
      - src/compression/core
      - src/compression/train.py
    outs:
      - ${model_path}
  compress:
    cmd: python -m compression compress
    params:
      - train_data
      - test_data
      - image_size
      - model_path
      - tflite_model_path
    deps:
      - ${train_data}
      - ${test_data}
      - src/compression/core
      - src/compression/compress.py
    outs:
      - ${tflite_model_path}
